### ISSUE TITLE
Reblog Function Parameters

### ISSUE THREAD

**Issue by ydaniels** [tumblr/pytumblr#62]
I think there is a problem with the reblog function, am getting 
TypeError: reblog() takes exactly 2 arguments (4 given)
 when i add my username and this 
 File "/pytumblr/helpers.py", line 41, in add_dot_tumblr
    if (len(args) > 1 and ("." not in args[1])):
TypeError: argument of type 'int' is not iterable
when i dont add a username.

**Comment by codingjester** [comment]
Could you provide an example of the function usage? I'll see if I can understand what you're doing from there.

**Comment by ydaniels** [comment]
e.g
If i have a  code like this
username='tumblrapp'
postid=12343
reblogkey='ddddd'
client.reblog(username,postid,reblogkey)
I get this Error TypeError: reblog() takes exactly 2 arguments (4 given)
I think the problem comes from the decorator function in helpers.py 
validate_blogname(fn)

**Comment by ydaniels** [comment]
Okay i fixed it by patching the function

**Comment by MistaCrowley** [comment]
As of version 0.0.6, grabbed from pip, I'm still having this same exact problem.
